### ISSUE TITLE
Jenkins job failing with latest pom

### ISSUE THREAD

**Issue by tferr** [tferr/ASA#14]
When I updated the pom-fiji (tferr@25f2c2e7), the jenkins job for Sholl Analysis [failed](http://jenkins.imagej.net/job/Sholl-Analysis/98/console). It seems that `pom-fiji-21.1.0` and later have set the jdk to version 1.8. Yet, the jenkins job is set to Java 1.6. Is this correct?

@ctrueden, @hinerm: 
How would I change the jenkins job to allow compilation with the latest `pom-fiji`? Using and outdated pom does not seem to be practical, and it already caused me to miss some recent IJ1changes (tferr@36f7fd0f).

**Comment by ctrueden** [comment]
I updated the Sholl-Analysis job to run with OpenJDK 8 from now on. This is how we are migrating everything Java 8: one component at a time...

**Comment by tferr** [comment]
Thanks! I will update the documentation to mention the plugin will now require Java 8.
