### ISSUE TITLE
sholl profile table can't export

### ISSUE THREAD

**Issue by hufanglq** [tferr/ASA#30]
The sholl profile table doesn't have buttons, such as File > Save As. So the table can't be export or save directly. While the Deprecated command-Sholl Analysis can do it.

**Comment by tferr** [comment]
@hufanglq, sorry for the late reply, Somehow I missed this..
The modern tables are provided by SciJava. That is currently a limitation, that I think was addressed while back, but somehow not yet available through the updater. See this [discussion](https://forum.image.sc/t/can-you-save-a-defaultgenerictable-displayed-with-uiservice/12036/7) for background info, and this [issue](https://github.com/imagej/imagej/pull/224) for updates

**Comment by tferr** [comment]
@hufanglq  Just wanted to mention that if you subscribe to the Neuroanatomy update site. you can export the table using commands in the File menu.

**Comment by tferr** [comment]
Also, with the new version 4.0.1 there is a new option that allows you to save all the analysis files (plots, tables, mask) to a common directory.
