### ISSUE TITLE
Comparator and ImageParser should not be discoverable

### ISSUE THREAD

**Issue by ctrueden** [tferr/ASA#31]
On [January 25, 2020 at 2:33 PM CST](https://gitter.im/scijava/scijava-common?at=5e2ca62c183449313bd956dc), @imagejan wrote:
<blockquote>

I discovered an issue with two Commands in Sholl_Analysis (@tferr):
```
[ERROR] java.lang.IllegalStateException: java.lang.InstantiationException: sholl.math.Comparator
    at org.scijava.command.CommandModuleItem.getDefaultValue(CommandModuleItem.java:179)
    at org.scijava.module.AbstractModuleItem.toString(AbstractModuleItem.java:80)
```
and
```
[ERROR] java.lang.IllegalStateException: java.lang.InstantiationException: sholl.parsers.ImageParser
    at org.scijava.command.CommandModuleItem.getDefaultValue(CommandModuleItem.java:179)
    at org.scijava.module.AbstractModuleItem.toString(AbstractModuleItem.java:80)
```

I guess these two should simply not be annotated with ContextCommand, since they’re visible=false anyway.

</blockquote>

The `@Plugin` annotation [on Comparator](https://github.com/tferr/ASA/blob/Sholl_Analysis-4.0.0/src/main/java/sholl/math/Comparator.java#L39) and [on ImageParser](https://github.com/tferr/ASA/blob/Sholl_Analysis-4.0.0/src/main/java/sholl/parsers/ImageParser.java#L47) should probably be removed. (Tangentially: the plugin type should probably be `type = Command.class` rather than `type = ContextCommand.class`—the latter is merely a concrete base class implementing `Command` for convenience, not intended to be used as its own plugin type.)

**Comment by tferr** [comment]
Thanks @ctrueden , @imagejan!
