### ISSUE TITLE
Sholl Mask on segmented, binary 2d image problem

### ISSUE THREAD

**Issue by cuskss** [tferr/ASA#33]
had a z-stack that was converted to a max projection z-project. After thresholding and converting to binary, setting up a sholl analysis with step size = 0 resulted in a sholl mask of one color. Increasing the step size showed a more accurate sholl mask, but did not stop at the ending radius. Appreciate any help on the matter. 
![github inquery](https://user-images.githubusercontent.com/64882527/81137018-38f27180-8f2b-11ea-8059-fa8eb6dd7363.JPG)

**Comment by tferr** [comment]
@cuskss, did the [black background setting](https://imagej.nih.gov/ij/docs/guide/146-29.html#infobox:blackBackground) change by any chance before processing this image relatively to the previous ones you processed? (see also [this example](https://imagej.net/Sholl_Analysis#Cf._Segmentation)). If not, can you share that image? I'm wondering if there is something about it that makes things go awry.

**Comment by tferr** [comment]
@cuskss , I'm assuming you are able to fix the problem. Will re-open the issue if otherwise

**Comment by cuskss** [comment]
Im sorry, im just seeing these. We are still having the error. Im currently out of office, but will send the raw image when i return later today.

Sent via the Samsung Galaxy S10e, an AT&T 5G Evolution capable smartphone

________________________________
